### ISSUE TITLE
무한 루프로 인한 에러 해결

### ISSUE THREAD

**Issue by ssoree912** [deep-blue-dream/myLittleLib#9]
데이터 두개 이상 만들면 무한루프가 돌기 시작했습니다. 
같이 해결해보아효오

**Comment by soulchicken** [comment]
링크 하나 올립니다.
순환참조에 대해서 한글로 자세히 알려주는 게시글이 있습니다.
DTO 객체를 저희가 활용해볼까요?
[링크](https://dev-coco.tistory.com/133)

**Comment by ssoree912** [comment]
저도 DTO를 활용해볼까했는데 DTO를 반환하는걸로 합시다..! 
controller에는 entity를 반환하는게 좋은게 아니라네용,,,
